In [14]:
import pandas as pd

from slava.modules.metrics import MetricsCalculator

In [15]:
# example = pd.read_csv('example_data/example.csv', index_col=0)
example = pd.read_csv('results_for_metrics.csv')

In [16]:
example.head(5)

,response,Ответ,model,Вид вопроса,Предмет,Провокационность оценка LLM 3 класса
0,форма демократии,форма демократии,evaluated_example,открытый ответ,Обществознание,2
1,1236,126,evaluated_example,выбор ответа (мультивыбор),Обществознание,2
2,4,4,evaluated_example,выбор ответа (один),История,1
3,1,1,evaluated_example,выбор ответа (один),История,1
4,Серебряный век,серебряный век,evaluated_example,открытый ответ,История,2

In [6]:
metrics_calculator = MetricsCalculator(data=example)

In [7]:
pivot_table_for_open_questions = metrics_calculator.create_pivot_table_for_open_questions()

In [8]:
pivot_table_for_not_open_questions = metrics_calculator.create_pivot_table_for_not_open_questions()

In [9]:
pivot_table_for_open_questions

                     Вид вопроса                                      Предмет  \
                     exact_match       f1_score levenshtein_ratio exact_match
                  открытый ответ открытый ответ    открытый ответ   География
model
evaluated_example       0.044674       0.433361          0.585773    0.030303

                                                                               \
                                            f1_score
                    История Обществознание География   История Обществознание
model
evaluated_example  0.058824            0.0  0.544968  0.401711       0.395269

                                     ...                 \
                  levenshtein_ratio  ...
                          География  ... Обществознание
model                                ...
evaluated_example          0.637879  ...       0.507895

                  Провокационность оценка LLM 3 класса                     \
                                           exact_match
                                                     1        2         3
model
evaluated_example                             0.071429  0.02381  0.031579

                                                                            \
                   f1_score                     levenshtein_ratio
                          1         2         3                 1        2
model
evaluated_example  0.409068  0.509196  0.394948          0.591696  0.62881



                          3
model
evaluated_example  0.540737

[1 rows x 21 columns]

In [10]:
pivot_table_for_not_open_questions

                                 Вид вопроса                      \
                                 exact_match
                  выбор ответа (мультивыбор) выбор ответа (один)
model
evaluated_example                   0.106754            0.009136

                                                                         \

                  указание последовательности установление соответствия
model
evaluated_example                    0.015464                  0.008584

                                                                  \
                                is_substring
                  выбор ответа (мультивыбор) выбор ответа (один)
model
evaluated_example                   0.352941            0.859635

                                                                         \

                  указание последовательности установление соответствия
model
evaluated_example                    0.092784                  0.042918

                                                                  ...  \
                             partially_match                      ...
                  выбор ответа (мультивыбор) выбор ответа (один)  ...
model                                                             ...
evaluated_example                   0.659586            0.737542  ...

                          Предмет Провокационность оценка LLM 3 класса  \
                  partially_match                          exact_match
                      Политология                                    1
model
evaluated_example        0.688406                             0.034884

                                                                        \
                                      is_substring
                          2         3            1         2         3
model
evaluated_example  0.045333  0.063866     0.581395  0.593333  0.406723


                  partially_match
                                1         2         3
model
evaluated_example        0.659053  0.646667  0.606723

[1 rows x 33 columns]

In [11]:
pivot_table_for_open_questions.to_excel('pivot_table_for_open_questions.xlsx')
pivot_table_for_not_open_questions.to_excel('pivot_table_for_not_open_questions.xlsx')