In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('results.csv')

In [5]:
df

,id,input,response,output
0,0,"Прочитайте приведённые далее задачу, текст и в...",форма демократии,форма демократии
1,1,Прочитайте приведённую далее задачу и выполнит...,1236,126
2,2,"Прочитайте приведённые далее задачу, текст и в...",4,4
3,3,"Прочитайте приведённые далее задачу, текст и в...",1,1
4,4,"Прочитайте приведённые далее задачу, текст и в...",Серебряный век,серебряный век
...,...,...,...,...
2835,2835,Прочитайте приведённую далее задачу и выполнит...,145,145
2836,2836,Прочитайте приведённую далее задачу и выполнит...,3,3
2837,2837,Прочитайте приведённую далее задачу и выполнит...,1,1
2838,2838,Прочитайте приведённую далее задачу и выполнит...,1,1
2839,2839,"Прочитайте приведённые далее задачу, текст и в...",Германией,германия

In [7]:
from slava.modules.data_loader import DataLoader

In [8]:
data_loader = DataLoader()
dataset = data_loader.load_data()
dataset.shape

(2840, 4)

In [9]:
dataset

,instruction,inputs,outputs,meta
0,"Прочитайте приведённые далее задачу, текст и в...","{'task': 'В приведенном ряду найдите понятие, ...",форма демократии,"{'subject': 'Обществознание', 'type': 'открыты..."
1,Прочитайте приведённую далее задачу и выполнит...,{'task': 'В стране Y создан Центр изучения гло...,126,"{'subject': 'Обществознание', 'type': 'выбор о..."
2,"Прочитайте приведённые далее задачу, текст и в...",{'task': 'Выберите подходящее окончание для фр...,4,"{'subject': 'История', 'type': 'выбор ответа (..."
3,"Прочитайте приведённые далее задачу, текст и в...",{'task': 'Выберите подходящее окончание для фр...,1,"{'subject': 'История', 'type': 'выбор ответа (..."
4,"Прочитайте приведённые далее задачу, текст и в...",{'task': 'Прочитайте отрывок из сочинения фило...,серебряный век,"{'subject': 'История', 'type': 'открытый ответ..."
...,...,...,...,...
2835,Прочитайте приведённую далее задачу и выполнит...,{'task': 'Что из перечисленного является приме...,145,"{'subject': 'География', 'type': 'выбор ответа..."
2836,Прочитайте приведённую далее задачу и выполнит...,{'task': 'В каком году была открыта Славяно-гр...,3,"{'subject': 'История', 'type': 'выбор ответа (..."
2837,Прочитайте приведённую далее задачу и выполнит...,{'task': 'Политическая организация ведёт актив...,1,"{'subject': 'Обществознание', 'type': 'выбор о..."
2838,Прочитайте приведённую далее задачу и выполнит...,{'task': 'Гражданин П. имеет собственный бизне...,1,"{'subject': 'Обществознание', 'type': 'выбор о..."
2839,"Прочитайте приведённые далее задачу, текст и в...",{'task': 'Прочитайте отрывок из постановления ...,германия,"{'subject': 'История', 'type': 'открытый ответ..."

In [46]:
dataset['meta'][4]

{'subject': 'История',
 'type': 'открытый ответ',
 'source': 'https://hist-ege.sdamgia.ru/problem?id=1227',
 'comment': None,
 'provac_score': 2}

In [10]:
df = df.drop(columns=['id', 'input'])

df['model'] = 'evaluated_example'
df['Вид вопроса'] = [meta['type'] for meta in dataset['meta']]
df['Предмет'] = [meta['subject'] for meta in dataset['meta']]
df['Провокационность оценка LLM 3 класса'] = [meta['provac_score'] for meta in dataset['meta']]

In [11]:
df = df.rename(columns={'output': 'Ответ'})

In [12]:
df.to_csv('results_for_metrics.csv', index = False)